version: "3.9"
services:
  web:
    image: altay
    container_name: altay
    build: .
    command: sh -c "python manage.py collectstatic --noinput &&
                    python manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8000 config.wsgi"
    restart: always
    ports:
      - "5900:8000"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
volumes:
  static_volume:
  media_volume: