# Generated by Django 4.1.2 on 2022-10-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pk'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
