# Generated by Django 4.1.2 on 2022-11-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='src',
            new_name='image',
        ),
    ]
