# Generated by Django 4.1.3 on 2022-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='build/file/', verbose_name='Сборка приложения')),
                ('image', models.ImageField(upload_to='build/image/', verbose_name='Картинка')),
                ('date', models.DateField(verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложение',
                'ordering': ['-pk'],
            },
        ),
    ]
