# Generated by Django 4.1.2 on 2022-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesoffline',
            name='services_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
