# Generated by Django 4.1.2 on 2022-11-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
