# Generated by Django 4.1.2 on 2022-11-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_delete_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сервисы',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['pk'],
            },
        ),
        migrations.RenameModel(
            old_name='ServicesOffline',
            new_name='ServicesForm',
        ),
        migrations.CreateModel(
            name='ServicesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.services')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
                'ordering': ['pk'],
            },
        ),
    ]
