# Generated by Django 4.1.2 on 2022-11-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_services_rename_servicesoffline_servicesform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesitem',
            old_name='title2',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='servicesitem',
            old_name='title1',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='servicesitem',
            old_name='title3',
            new_name='phone',
        ),
    ]
