# Generated by Django 4.1.3 on 2022-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_title2_servicesitem_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.JSONField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='servicesitem',
            name='services',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='qwe'),
        ),
    ]
