# Generated by Django 4.1.2 on 2022-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(blank=True, max_length=64, null=True)),
                ('family_status', models.CharField(blank=True, max_length=64, null=True)),
                ('child_age', models.CharField(blank=True, max_length=64, null=True)),
                ('disabled_person', models.CharField(blank=True, max_length=64, null=True)),
                ('limited_person', models.CharField(blank=True, max_length=64, null=True)),
                ('specialist', models.CharField(blank=True, max_length=64, null=True)),
                ('counseling_theme', models.CharField(blank=True, max_length=64, null=True)),
                ('other', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
