# Generated by Django 4.1.3 on 2022-11-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-pk'], 'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Форма обратной связи'},
        ),
    ]
