# Generated by Django 4.1.3 on 2022-12-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Форма обратной связи'},
        ),
    ]
