# Generated by Django 4.1.2 on 2022-11-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'ordering': ['pk'], 'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
    ]
