# Generated by Django 4.1.2 on 2022-10-26 09:23

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailcode_alter_user_options_user_lastname_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='code',
            field=models.CharField(default=apps.users.utils.Util.generate_code, max_length=6, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='email'),
        ),
    ]
