# Generated by Django 4.1.3 on 2022-11-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'ordering': ['pk'], 'verbose_name': 'Ребенка', 'verbose_name_plural': 'Дети'},
        ),
    ]
