# Generated by Django 4.1.2 on 2022-10-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_games_gamesimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gamesimages',
            options={'verbose_name': 'Картинки для игр', 'verbose_name_plural': 'Картинки для игр'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-pk'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
