# Generated by Django 4.1.2 on 2022-11-01 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_games_options_alter_gamesimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['pk'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='gamesimages',
            name='games',
        ),
        migrations.AddField(
            model_name='gamesimages',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='information.games'),
            preserve_default=False,
        ),
    ]
