# Generated by Django 4.1.2 on 2022-11-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_rename_src_gamesimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gamesimages',
            name='image',
            field=models.ImageField(upload_to='images/games/', verbose_name='Картинка'),
        ),
    ]
