# Generated by Django 4.1.2 on 2022-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_games_description_alter_games_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=123, verbose_name='Описание видео'),
            preserve_default=False,
        ),
    ]
