# Generated by Django 4.1.2 on 2022-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание видео'),
        ),
    ]
