# Generated by Django 4.1.2 on 2022-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_alter_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='VK')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
