# Generated by Django 4.1.2 on 2022-11-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Ссылка на youtube канал')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutdocs',
            options={'verbose_name': 'Документация в разделе о нас', 'verbose_name_plural': 'Документация в разделе о нас'},
        ),
        migrations.AlterField(
            model_name='aboutdocs',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='docs/about/'),
        ),
        migrations.CreateModel(
            name='RecommendationsDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('docs', models.FileField(blank=True, null=True, upload_to='docs/recommendations/')),
                ('recommendations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='information.recommendations')),
            ],
            options={
                'verbose_name': 'Методические материалы',
                'verbose_name_plural': 'Методические материалы',
            },
        ),
    ]
