# Generated by Django 4.1.2 on 2022-11-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_recommendations_alter_aboutdocs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name': 'Рекомендации', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AddField(
            model_name='aboutdocs',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='information.about'),
            preserve_default=False,
        ),
    ]
