# Generated by Django 4.1.2 on 2022-11-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0013_alter_recommendations_options_aboutdocs_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Полезная информация/Игры для развития', 'verbose_name_plural': 'Полезная информация/Игры для развития'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name': 'Полезная информация/Рекомендации', 'verbose_name_plural': 'Полезная информация/Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['pk'], 'verbose_name': 'Полезная информация/Видеоуроки', 'verbose_name_plural': 'Полезная информация/Видеоуроки'},
        ),
    ]
