# Generated by Django 4.1.3 on 2022-11-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0014_alter_games_options_alter_recommendations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игры для развития', 'verbose_name_plural': 'Игры для развития'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name': 'Рекомендации', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['pk'], 'verbose_name': 'Видеоуроки', 'verbose_name_plural': 'Видеоуроки'},
        ),
    ]
