# Generated by Django 4.1.3 on 2022-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0015_alter_games_options_alter_recommendations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdocs',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='docs/about/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='recommendationsdocs',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='docs/recommendations/', verbose_name='Документ'),
        ),
    ]
