# Generated by Django 4.1.3 on 2023-05-29 09:53

import apps.catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя картинки')),
                ('alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Альт текст')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/', validators=[apps.catalog.models.validate_image_extension], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '1.2 - Изображение',
                'verbose_name_plural': '1.2 - Изображения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContentPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя файла')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('autoOpen', models.BooleanField(default=True, verbose_name='Развернут')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF-файл')),
            ],
            options={
                'verbose_name': '1.3 - PDF-файл',
                'verbose_name_plural': '1.3 - PDF-файлы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug-поле')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='Путь к странице')),
            ],
            options={
                'verbose_name': '0 - Раздел',
                'verbose_name_plural': '0 - Разделы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TableAboutCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Место нахождения учреждения')),
                ('contacts', models.CharField(max_length=255, verbose_name='Телефоны/факс')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('worktime', models.CharField(max_length=255, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': '2 - Таблица - О центре',
                'verbose_name_plural': '2 - Таблица - О центре',
            },
        ),
        migrations.CreateModel(
            name='TableContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': '3 - Таблица - Контакты',
                'verbose_name_plural': '3 - Таблица - Контакты',
            },
        ),
        migrations.CreateModel(
            name='TableDepartmentCMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('worktime', models.CharField(max_length=255, verbose_name='Режим Работы')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Таблица - Отделение социально-медицинской реабилитации',
                'verbose_name_plural': 'Таблица - Отделение социально-медицинской реабилитации',
            },
        ),
        migrations.CreateModel(
            name='TableDepartmentDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('worktime', models.CharField(max_length=255, verbose_name='Режим Работы')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Таблица - Отделение дневного пребывания',
                'verbose_name_plural': 'Таблица - Отделение дневного пребывания',
            },
        ),
        migrations.CreateModel(
            name='TableDepartmentOMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('worktime', models.CharField(max_length=255, verbose_name='Режим Работы')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Таблица - Отделение организационно-методической работы',
                'verbose_name_plural': 'Таблица - Отделение организационно-методической работы',
            },
        ),
        migrations.CreateModel(
            name='TableDepartmentPPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('worktime', models.CharField(max_length=255, verbose_name='Режим Работы')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Таблица - Отделение психолого-педагогической помощи',
                'verbose_name_plural': 'Таблица - Отделение психолого-педагогической помощи',
            },
        ),
        migrations.CreateModel(
            name='TableDepartmentSt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('worktime', models.CharField(max_length=255, verbose_name='Режим Работы')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Таблица - Стационарное отделение',
                'verbose_name_plural': 'Таблица - Стационарное отделение',
            },
        ),
        migrations.CreateModel(
            name='TableWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255, verbose_name='Дни недели')),
                ('time', models.CharField(max_length=255, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': '4 - Таблица - Режим работы',
                'verbose_name_plural': '4 - Таблица - Режим работы',
            },
        ),
        migrations.CreateModel(
            name='SectionPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.PositiveBigIntegerField(verbose_name='Номер телефона')),
                ('formatNumber', models.CharField(max_length=50, verbose_name='Номер телефона форматированный')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_phone', to='catalog.sections', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': '1.5 - Единый контактный центр',
                'verbose_name_plural': '1.5 - Единый контактный центр',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SectionPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255, verbose_name='Путь к картинке')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на ресурс')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_partner', to='catalog.sections', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': '1.6 - Партнера',
                'verbose_name_plural': '1.6 - Партнеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SectionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Текст/Описание')),
                ('image', models.CharField(max_length=255, verbose_name='Путь к картинке')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_app', to='catalog.sections', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': '1.4 - Приложение Открытый мир',
                'verbose_name_plural': '1.4 - Приложение Открытый мир',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='SLUG')),
                ('path', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Путь к странице')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название страницы')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='catalog.sections', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': '1 - Страницу',
                'verbose_name_plural': '1 - Страницы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('img', 'Изображение'), ('pdf', 'PDF-файл'), ('table_horizontal', 'Горизонтальная таблица'), ('table_vertical', 'Вертикальная таблица')], max_length=20, verbose_name='Тип контента')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['tablecontacts', 'tableworktime', 'tabledepartmentomr', 'tabledepartmentst', 'tabledepartmentppp', 'tabledepartmentcmr', 'tabledepartmentdp']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Вертикальная таблица')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='catalog.elements', verbose_name='Страница')),
                ('img', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.contentimg', verbose_name='Картинка')),
                ('pdf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.contentpdf', verbose_name='PDF-файл')),
                ('table_horizontal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tableaboutcenter')),
            ],
            options={
                'verbose_name': '1.1 - Контент страницы',
                'verbose_name_plural': '1.1 - Контент страниц',
                'ordering': ['id'],
            },
        ),
    ]
