# Generated by Django 4.1.3 on 2023-05-30 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_location_tableaboutcenter_content_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GosTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.contentpdf', verbose_name='PDF-файл')),
            ],
            options={
                'verbose_name': '1.1 - Государственное задание',
                'verbose_name_plural': '1.1 - Государственное задание',
                'ordering': ['-id'],
            },
        ),
    ]
