# Generated by Django 4.1.3 on 2023-05-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_gostask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableaboutcenter',
            options={'ordering': ['id'], 'verbose_name': '2 - Таблица - О центре', 'verbose_name_plural': '2 - Таблица - О центре'},
        ),
        migrations.AlterModelOptions(
            name='tablecontacts',
            options={'ordering': ['id'], 'verbose_name': '3 - Таблица - Контакты', 'verbose_name_plural': '3 - Таблица - Контакты'},
        ),
        migrations.AlterModelOptions(
            name='tabledepartmentcmr',
            options={'ordering': ['id'], 'verbose_name': 'Таблица - Отделение социально-медицинской реабилитации', 'verbose_name_plural': 'Таблица - Отделение социально-медицинской реабилитации'},
        ),
        migrations.AlterModelOptions(
            name='tabledepartmentdp',
            options={'ordering': ['id'], 'verbose_name': 'Таблица - Отделение дневного пребывания', 'verbose_name_plural': 'Таблица - Отделение дневного пребывания'},
        ),
        migrations.AlterModelOptions(
            name='tabledepartmentomr',
            options={'ordering': ['id'], 'verbose_name': 'Таблица - Отделение организационно-методической работы', 'verbose_name_plural': 'Таблица - Отделение организационно-методической работы'},
        ),
        migrations.AlterModelOptions(
            name='tabledepartmentppp',
            options={'ordering': ['id'], 'verbose_name': 'Таблица - Отделение психолого-педагогической помощи', 'verbose_name_plural': 'Таблица - Отделение психолого-педагогической помощи'},
        ),
        migrations.AlterModelOptions(
            name='tabledepartmentst',
            options={'ordering': ['id'], 'verbose_name': 'Таблица - Стационарное отделение', 'verbose_name_plural': 'Таблица - Стационарное отделение'},
        ),
        migrations.AlterModelOptions(
            name='tableworktime',
            options={'ordering': ['id'], 'verbose_name': '4 - Таблица - Режим работы', 'verbose_name_plural': '4 - Таблица - Режим работы'},
        ),
    ]
