# Generated by Django 4.1.2 on 2022-10-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCode',
        ),
    ]
